import type { WebhookHandler } from "~/lib/appapprove-config";
import type { Env } from "../../load-context";
import { and, eq } from "drizzle-orm";
import { upsertResource, recordDeadLetter } from "~/lib/sync.server";
import { getDb } from "~/lib/db/client.server";
import { subscriptions } from "~/lib/db/app-tables.schema.server";
import { cancelSubscription } from "~/lib/subscriptions.server";

// SubSave — orders/cancelled. Two effects:
//   1. Mirror the cancel into the local orders table (sync layer).
//   2. If the cancelled order was created by a renewal charge (we record
//      shopify_order_id on subscription_charges once Sprint 25 codegen
//      wires the Draft-Order call), we leave the subscription alone —
//      merchants cancel individual orders without intending to cancel
//      the recurring relationship. The customer-initiated subscription
//      cancel flow runs through the admin/storefront UI instead.
//
// Edge case handled: if the order metadata flags it as a one-off
// generated by the renewals cron AND the customer asked the merchant to
// stop deliveries, the merchant can pass `subsave_cancel: "true"` in
// the cancel reason note — we honor that and cancel the matching active
// subscriptions.

interface ShopifyOrderPayload {
  admin_graphql_api_id: string;
  name: string;
  email: string | null;
  total_price: string | null;
  currency: string | null;
  financial_status: string | null;
  fulfillment_status: string | null;
  cancel_reason: string | null;
  note?: string | null;
  customer?: { admin_graphql_api_id?: string } | null;
  updated_at: string;
}

const handler: WebhookHandler = async ({ shop, payload, context }) => {
  const env = (context.cloudflare?.env ?? {}) as Env;
  if (!env.D1) return new Response("OK (no D1)", { status: 200 });
  const p = payload as ShopifyOrderPayload;
  if (!p.admin_graphql_api_id) return new Response("Bad payload", { status: 400 });

  try {
    await upsertResource(env.D1, {
      shop,
      resource: "orders",
      remoteId: p.admin_graphql_api_id,
      remoteUpdatedAt: p.updated_at,
      row: {
        remoteId: p.admin_graphql_api_id,
        shop,
        name: p.name,
        email: p.email,
        totalPrice: p.total_price,
        currencyCode: p.currency,
        financialStatus: p.financial_status,
        fulfillmentStatus: p.fulfillment_status,
        payload: p as unknown as Record<string, unknown>,
        remoteUpdatedAt: p.updated_at,
      },
    });
  } catch (err) {
    await recordDeadLetter(env.D1, {
      shop,
      resource: "orders",
      remoteId: p.admin_graphql_api_id,
      payload: p as unknown as Record<string, unknown>,
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }

  // Optional subscription-cascade: the merchant signals intent via a
  // structured note. Keep this conservative — bulk-cancelling all of a
  // customer's subscriptions on every cancelled order would surprise
  // merchants who issue refunds without intending to end the recurring
  // relationship.
  const noteHint = (p.note ?? "").toLowerCase();
  if (noteHint.includes("subsave_cancel") && p.customer?.admin_graphql_api_id) {
    const db = getDb(env.D1);
    const customerId = p.customer.admin_graphql_api_id;
    const active = await db
      .select({ id: subscriptions.id })
      .from(subscriptions)
      .where(
        and(
          eq(subscriptions.shop, shop),
          eq(subscriptions.customerRemoteId, customerId),
          eq(subscriptions.status, "active"),
        ),
      );
    for (const sub of active) {
      await cancelSubscription(env.D1, sub.id, "merchant_cancelled_via_order_note");
    }
  }

  return new Response("OK", { status: 200 });
};

export default handler;
